ft(tests)Change command of running tests to > stringclass@1.0.0 test /Users/carolinewanjiku/stringclass > babel-node spec/stringclass.spec.js
Started
[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m

Failures:
1) the hasVowels method returns true if the string contains vowels returns true if vowel found
  Message:
[31m    Expected undefined to be true.[0m
  Stack:
    Error: Expected undefined to be true.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:12:28)

2) the hasVowels method returns true if the string contains vowels returns message if no vowel found
  Message:
[31m    Expected undefined to equal 'There must be a string'.[0m
  Stack:
    Error: Expected undefined to equal 'There must be a string'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:16:36)

3) The toUpper method converts a string to uppercase returns capital if conversion successful
  Message:
[31m    ReferenceError: testString is not defined[0m
  Stack:
    ReferenceError: testString is not defined
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:22:43)

4) The toUpper method converts a string to uppercase returns message if string was already in uppercase
  Message:
[31m    Expected undefined to equal 'String is already in uppercase'.[0m
  Stack:
    Error: Expected undefined to equal 'String is already in uppercase'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:27:27)

5) The toLower method converts a string to lowercase returns lowercase string if conversion successful
  Message:
[31m    Expected undefined to equal 'behavioural science'.[0m
  Stack:
    Error: Expected undefined to equal 'behavioural science'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:34:27)

6) The toLower method converts a string to lowercase returns message if string was already in lowercase
  Message:
[31m    Expected stringClass({ name: 'behavioural science' }) to equal 'String already in lowercase'.[0m
  Stack:
    Error: Expected stringClass({ name: 'behavioural science' }) to equal 'String already in lowercase'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:38:27)

7) ucFirst converts the first letter of a string to uppercase returns true if conversion successful
  Message:
[31m    Expected undefined to equal 'Hippopotamus'.[0m
  Stack:
    Error: Expected undefined to equal 'Hippopotamus'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:45:29)

8) ucFirst converts the first letter of a string to uppercase returns message if first letter was already uppercase
  Message:
[31m    Expected undefined to equal 'The first character is already in uppercase'.[0m
  Stack:
    Error: Expected undefined to equal 'The first character is already in uppercase'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:49:29)

9) The isQuestion returns true if string is a question returns true string is question
  Message:
[31m    Expected undefined to be true.[0m
  Stack:
    Error: Expected undefined to be true.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:56:32)

10) The isQuestion returns true if string is a question returns false if string not question
  Message:
[31m    Expected undefined to be false.[0m
  Stack:
    Error: Expected undefined to be false.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:60:32)

11) The in method returns a list of the words in the string, as an array returns true if string returned as array
  Message:
[31m    Expected undefined to equal [ 'This', 'is', 'a', 'string' ].[0m
  Stack:
    Error: Expected undefined to equal [ 'This', 'is', 'a', 'string' ].
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:67:29)
  Message:
[31m    TypeError: Cannot read property 'length' of undefined[0m
  Stack:
    TypeError: Cannot read property 'length' of undefined
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:68:16)

12) The in method returns a list of the words in the string, as an array returns message if string is already an array
  Message:
[31m    Expected undefined to equal 'This is already an array'.[0m
  Stack:
    Error: Expected undefined to equal 'This is already an array'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:72:29)

13) The wordCount method returns the number of words in the string returns true when word count is returned
  Message:
[31m    Expected undefined to equal 2.[0m
  Stack:
    Error: Expected undefined to equal 2.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:79:29)

14) The toCurrency method returns a currency representation of the String returns message if string not a number
  Message:
[31m    Expected undefined to equal 'This is not a number'.[0m
  Stack:
    Error: Expected undefined to equal 'This is not a number'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:86:32)

15) The toCurrency method returns a currency representation of the String returns true if string is converted to currency form
  Message:
[31m    Expected undefined to equal '35,876,569'.[0m
  Stack:
    Error: Expected undefined to equal '35,876,569'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:90:32)

16) The fromCurrency method returns a number representation of the Currency String returns message if string is not number
  Message:
[31m    Expected undefined to equal 'This is not a number'.[0m
  Stack:
    Error: Expected undefined to equal 'This is not a number'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:98:32)

17) The fromCurrency method returns a number representation of the Currency String returns true if number representation returned
  Message:
[31m    Expected undefined to equal '35876569'.[0m
  Stack:
    Error: Expected undefined to equal '35876569'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:102:32)

18) The inverseCase method returns each letter in the string as an inverse of its current case returns message if string empty
  Message:
[31m    Expected undefined to equal 'hELLO wORLD'.[0m
  Stack:
    Error: Expected undefined to equal 'hELLO wORLD'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:110:31)

19) The alternateCase method returns the letters in alternating cases returns true of alternated string returned
  Message:
[31m    TypeError: (intermediate value).alternateCase is not a function[0m
  Stack:
    TypeError: (intermediate value).alternateCase is not a function
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:116:64)

20) The getMiddle method returns the character(s) in the middle of the string returns true if character in middle returned
  Message:
[31m    Expected undefined to equal 't'.[0m
  Stack:
    Error: Expected undefined to equal 't'.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:124:30)

21) The numberWords method returns the numbers in words returns message if string is not a number
  Message:
[31m    Expected undefined to equal 4.[0m
  Stack:
    Error: Expected undefined to equal 4.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:131:30)

22) The isDigit method returns true if the string is a digit returns true if string is a single digit
  Message:
[31m    Expected undefined to be true.[0m
  Stack:
    Error: Expected undefined to be true.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:138:29)

23) The isDigit method returns true if the string is a digit returns false string is more than one digit
  Message:
[31m    Expected undefined to be false.[0m
  Stack:
    Error: Expected undefined to be false.
        at UserContext.<anonymous> (/Users/carolinewanjiku/stringclass/spec/stringclass.spec.js:142:29)

23 specs, 23 failures
Finished in 0.06 seconds in README